# Generated by Django 4.1.2 on 2022-10-11 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=150, verbose_name='Название банка')),
                ('term_min', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Срок ипотеки, от ')),
                ('term_max', models.IntegerField(default=30, validators=[django.core.validators.MaxValueValidator(30)], verbose_name='Срок ипотеки, до')),
                ('rate_min', models.FloatField(default=1.8, verbose_name='Ставка от (%)')),
                ('rate_max', models.FloatField(default=9.8, verbose_name='Ставка до (%)')),
                ('payment_min', models.IntegerField(default=1000000, verbose_name='Сумма кредита, от')),
                ('payment_max', models.IntegerField(default=10000000, verbose_name='Сумма кредита, до')),
            ],
            options={
                'verbose_name': 'Предложение по ипотеке',
                'verbose_name_plural': 'Предложения по ипотеке',
            },
        ),
    ]
